/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pengaduan;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Locale;

/**
 *
 * @author desta
 */
public class tanggapan extends javax.swing.JFrame {
    java.util.Date tglsekarang = new java.util.Date();
    SimpleDateFormat fm=new SimpleDateFormat("dd MMMMMMMMM yyyy", Locale.getDefault());
    
    Connection con;
    DefaultTableModel tm,tml,tmt;

    /**
     * Creates new form order
     */
    public void connect(){
    con=null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://127.0.0.1/pengaduan_masyarakat","root","");
        }catch(Exception e){
        System.out.print("ERROR KUERI KE DATABASE:\n"+ e +"\n\n");
    }
    }
    
    private void refreshTablepengaduan(){

    tml = new DefaultTableModel(null,
    new Object[] {"id pengaduan","tangggal","nik","pengaduan","gambar","status"});
    tblpengaduan.setModel(tml);
    tml.getDataVector().removeAllElements();
    try{
        PreparedStatement s= con.prepareStatement("SELECT * FROM pengaduan");
        ResultSet r = s.executeQuery();
        while(r.next()){
        Object[] data ={
        r.getString(1),
        r.getString(2),
        r.getString(3),
        r.getString(4),
        r.getString(5),
        r.getString(6)
        };
        tml.addRow(data);
        }
    }catch(Exception e){
    System.out.print("ERROR KUERI KE DATABAE:\n"+ e +"\n\n");
    }
}
    
    private void refreshTablepetugas(){

    tm = new DefaultTableModel(null,
    new Object[] {"id petugas","nama","telp","level"});
    tblpetugas.setModel(tm);
    tm.getDataVector().removeAllElements();
    try{
        PreparedStatement s= con.prepareStatement("SELECT id_petugas,nama_petugas,telp,level FROM petugas");
        ResultSet r = s.executeQuery();
        while(r.next()){
        Object[] data ={
        r.getString(1),
        r.getString(2),
        r.getString(3),
        r.getString(4)
        };
        tm.addRow(data);
        }
    }catch(Exception e){
    System.out.print("ERROR KUERI KE DATABAE:\n"+ e +"\n\n");
    }
}
    
    private void refreshTabletanggapan(){

    tmt = new DefaultTableModel(null,
    new Object[] {"id tanggapan","id pengaduan","tgl tanggapan","tanggapan","id petugas"});
    tbltanggapan.setModel(tmt);
    tmt.getDataVector().removeAllElements();
    try{
        PreparedStatement s= con.prepareStatement("SELECT * FROM tanggapan");
        ResultSet r = s.executeQuery();
        while(r.next()){
        Object[] data ={
        r.getString(1),
        r.getString(2),
        r.getString(3),
        r.getString(4),
        r.getString(5)
        };
        tmt.addRow(data);
        }
    }catch(Exception e){
    System.out.print("ERROR KUERI KE DATABAE:\n"+ e +"\n\n");
    }
}
    private void disabled(){
        txttanggal.setEnabled(false);
        txtnik.setEnabled(false);
        txtaduan.setEnabled(false);
    }
    
    private void id_otomatis(){
    try{
        Connection c = con;
        Statement s = c.createStatement();
        String sql = "SELECT * FROM tanggapan ORDER BY id_tanggapan DESC";
        ResultSet r = s.executeQuery(sql);
        if (r.next()){
            String No = r.getString("id_pengaduan");
            String otomatis = "" +(Integer.parseInt(No)+1);
            txtidtang.setText(otomatis);
        }else {
            txtidtang.setText("1");
        }
        r.close();
        s.close();
    }catch(Exception e){
        System.out.print("EROR KUERI KE DATABASE:\n" + e + "\n\n");
    }
}
    private void tampil_tanggal(){
        String tanggal = fm.format(tglsekarang);
        txttgl.setText(tanggal);
    }
    
    private void kosong(){
        txtidpeng.setEnabled(false);
        txttanggapan.setEnabled(false);
    }

    /**
     * Creates new form tanggapan
     */
    public tanggapan() {
        initComponents();
        connect();
        refreshTablepengaduan();
        disabled();
        refreshTablepetugas();
        id_otomatis();
        tampil_tanggal();
        refreshTabletanggapan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txttanggal = new javax.swing.JTextField();
        gambar = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpengaduan = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaduan = new javax.swing.JTextArea();
        txtnik = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblpetugas = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        txttanggapan = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtidtang = new javax.swing.JTextField();
        txtidpeng = new javax.swing.JTextField();
        txttgl = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbltanggapan = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtidpet = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txttanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanggalActionPerformed(evt);
            }
        });

        gambar.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        gambar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gambar.setText("gambar");
        gambar.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gambar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gambarMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("tanggal");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("nik");

        tblpengaduan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpengaduan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpengaduanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpengaduan);

        txtaduan.setColumns(20);
        txtaduan.setRows(5);
        jScrollPane2.setViewportView(txtaduan);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("pengaduan");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pengaduan");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("tanggapi");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("id tanggapan");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("id pengaduan");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("tgl tanggapan");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("tanggapan");

        tblpetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpetugasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblpetugas);

        txttanggapan.setColumns(20);
        txttanggapan.setRows(5);
        jScrollPane4.setViewportView(txttanggapan);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("petugas");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("pengaduan");

        txtidpeng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpengActionPerformed(evt);
            }
        });

        tbltanggapan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbltanggapan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltanggapanMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbltanggapan);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton1.setText("Tanggapi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("id petugas");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("tanggapan");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setText("Tanggapan");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jButton2.setText("hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtnik, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidtang, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtidpeng, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtidpet, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(238, 238, 238))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jButton2)
                        .addGap(39, 39, 39)
                        .addComponent(jButton3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel11))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(290, 290, 290))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(63, 63, 63)
                                .addComponent(gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(137, 137, 137)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtidtang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtidpeng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtidpet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttanggalActionPerformed

    private void tblpengaduanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpengaduanMouseClicked
        // TODO add your handling code here:
        int i = tblpengaduan.getSelectedRow();
        if (i==-1){
            return;
        }
        String idpeng=(String)tml.getValueAt(i, 0);
        txtidpeng.setText(idpeng);
        String tanggal=(String)tml.getValueAt(i, 1);
        txttanggal.setText(tanggal);
        String nik=(String)tml.getValueAt(i, 2);
        txtnik.setText(nik);
        String aduan=(String)tml.getValueAt(i, 3);
        txtaduan.setText(aduan);
        String photo=(String)tml.getValueAt(i, 4);
        ImageIcon icon=new ImageIcon(new ImageIcon(photo).getImage().getScaledInstance(gambar.getWidth(),
        gambar.getHeight(),Image.SCALE_SMOOTH));
        gambar.setIcon(icon);
    }//GEN-LAST:event_tblpengaduanMouseClicked

    private void txtidpengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpengActionPerformed

    private void tblpetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpetugasMouseClicked
        // TODO add your handling code here:
        int i = tblpetugas.getSelectedRow();
        if (i==-1){
            return;
        }
        String tanggal=(String)tm.getValueAt(i, 0);
        txtidpet.setText(tanggal);
    }//GEN-LAST:event_tblpetugasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // TODO add your handling code here:
        SimpleDateFormat fm2 = new SimpleDateFormat("yyyy-MM-dd", Locale.getDefault());
        String tanggal = fm2.format(tglsekarang);
        try{
            Connection c=con;
            int baris=tbltanggapan.getRowCount();
            for (int a=0; a < baris; a++){
                id_otomatis();
                PreparedStatement ps=con.prepareStatement("INSERT INTO tanggapan VALUES (?,?,?,?,?)");
                ps.setString(1, txtidtang.getText());
                ps.setString(2, txtidpeng.getText());
                ps.setString(3, tanggal);
                ps.setString(4, txttanggapan.getText());
                ps.setString(5, txtidpet.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "tanggapan tersimpan");
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "gagal tersimpan");
        }    
    refreshTabletanggapan();
    kosong();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void gambarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gambarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gambarMouseClicked

    private void tbltanggapanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltanggapanMouseClicked
        // TODO add your handling code here:
        int i = tbltanggapan.getSelectedRow();
        if (i==-1){
            return;
        }
        String id=(String)tmt.getValueAt(i, 0);
        txtidpeng.setText(id);
        String idtanggapan=(String)tmt.getValueAt(i, 0);
        txtidtang.setText(idtanggapan);
        String idpeng=(String)tmt.getValueAt(i, 1);
        txtidpeng.setText(idpeng);
        String tgl=(String)tmt.getValueAt(i, 2);
        txttgl.setText(tgl);
        String aduan=(String)tmt.getValueAt(i, 3);
        txttanggapan.setText(aduan);
        String idpet=(String)tmt.getValueAt(i, 4);
        txtidpet.setText(idpet);
    }//GEN-LAST:event_tbltanggapanMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        login_petugas lg = new login_petugas();
        int jawab = JOptionPane.showOptionDialog(this,
                "Yakin ingin logout?",
                "logout",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(jawab == JOptionPane.YES_OPTION){
            setVisible(false);
            lg.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        connect();
        int ok = JOptionPane.showConfirmDialog(null, "Anda yakin ingin menghapus tanggapan ini='"+
        txtidtang.getText()+"'",".:: konfirmasi ::.",JOptionPane.YES_NO_OPTION);
        if(ok==0){
            try{
                PreparedStatement ps=con.prepareStatement("DELETE FROM tanggapan WHERE id_tanggapan=?");
                ps.setString(1, txtidtang.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Tanggapan telah terhapus");
            }catch(Exception e){
             System.out.print("ERROR KUERI KE DATABASE:\n"+ e +"\n\n");
            }
        }
        refreshTabletanggapan();
        kosong();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tanggapan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tanggapan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gambar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblpengaduan;
    private javax.swing.JTable tblpetugas;
    private javax.swing.JTable tbltanggapan;
    private javax.swing.JTextArea txtaduan;
    private javax.swing.JTextField txtidpeng;
    private javax.swing.JTextField txtidpet;
    private javax.swing.JTextField txtidtang;
    private javax.swing.JTextField txtnik;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JTextArea txttanggapan;
    private javax.swing.JTextField txttgl;
    // End of variables declaration//GEN-END:variables
}
